qir-alliance/qcor

README.md
The ln command was misspelled as ls.
Tested by: viewing README on Github after pushing.
=> Fixing a minor typo in README

examples/qrt/CMakeLists.txt, examples/qrt/multiple_kernels.cpp, examples/qrt/multiple_kernels_Bell_test.cpp, examples/qrt/qft.hpp, examples/qrt/qpe_example_qrt.cpp, handlers/token_collector/token_collector_util.cpp, runtime/qcor.hpp, runtime/qrt/qrt.cpp, runtime/qrt/qrt.hpp
Changes:
- Added QRT supports for 2-qubit gates.
- Supported kernel calls (define kernels and use them within another kernel body).
- Added a couple of examples, including a simple QPE.
Note: for the QPE example, I'm using a hard-coded controlled oracle atm.
I'll look into porting the C-U circuit to the QRT later.
=> Update quantum runtime 

runtime/qrt/qrt_mapper.hpp
QRT function for the U3 gate is named "u3".
Signed-off-by: Thien Nguyen <nguyentm@ornl.gov>
=> Fixed qrt codegen mapping for U3 gate

examples/placement/simplePlacement.cpp, handlers/qcor_syntax_handler.cpp, runtime/qcor.hpp, runtime/qrt/pass_manager.cpp, runtime/qrt/pass_manager.hpp, runtime/qrt/qrt.cpp, runtime/qrt/qrt.hpp, tools/driver/qcor.in
Added 2 CLI options: `-qubit-map` and `-placement`.
Usage: 
- `-qubit-map 3,4,2,1,0` to pass a qubit map => `default-placement` will always be used.
- If no `-qubit-map`, default placement of `swap-shortest-path` will be used **only if** the qpu has connectivity graph defined. Other connectivity-based placement plugins can be used instead by passing a name to `-placement`.
=> Added placement to runtime PassManager

examples/CMakeLists.txt, examples/ftqc_qrt/bit-flip-code.cpp, examples/ftqc_qrt/error_correcting_code.cpp, examples/ftqc_qrt/five_qubit_qec_code.cpp, examples/ftqc_qrt/steane_qec_code.cpp, lib/impl/bit_flip_code.hpp, lib/impl/common.hpp, lib/impl/five_qubit_code.hpp, lib/impl/qec_factory.hpp, lib/impl/qec_utils.hpp, lib/impl/seven_qubit_steane_code.hpp, lib/qcor_qec
Each code is structured as a 3-member tuple: an operation to encode a phycical qubit into a logical register, an operation to decode syndromes and fix correctable errors, and the stabilizers. 
Added a util function to measure stabilizers with an ancillary qubit.
Added sample test drivers to validate those codes.
=> Implements some QEC codes in QCOR lib

handlers/token_collector/pyxasm/pyxasm_visitor.hpp, python/qcor.py, python/tests/test_kernel_jit.py, runtime/kernel/quantum_kernel.hpp, runtime/utils/qcor_utils.cpp
- Parse adjoint and ctrl dependency.
- Complete the `qpe` unit test and add a unit test for adjoint.
- Handle kernel names that are the same as a XACC circuit name, e.g. iqft.
- Fix a bug in adjoint circuit construction.
Related to https://github.com/ORNL-QCI/qcor/issues/47
=> More work on ctrl and adjoint

examples/qsim/TdWorkflowHeisenbergModel.cpp, examples/qsim/TrotterTdWorkflow.cpp, examples/qsim/VerifiedQuantumPhaseEstimation.cpp, lib/qsim/base/qcor_qsim.cpp, lib/qsim/base/qcor_qsim.hpp, lib/qsim/impls/cost_evaluator/partial_tomography.cpp, lib/qsim/impls/cost_evaluator/partial_tomography.hpp, lib/qsim/impls/workflow/time_dependent.cpp, python/examples/qsim_example.py, python/examples/qsim_heisenberg_model.py, python/py-qcor.cpp, python/tests/test_qsim.py
- Parameters for Jx, Jy, Jz static terms as well as the external time-dependent field (along X, Y, or Z-axis).
- Added an example (C++ and Python) derived from ArQTiC.
- Added ability to observe an array of kernels, which is a common use case for time-dependent simulation.
Tested by: running the example and comparing the results with ArQTiC simulation.
=> Ability to load parameterized Heisenberg model

python/qcor.in.py, python/tests/CMakeLists.txt, python/tests/test_kernel_jit.py
Resolve https://github.com/ORNL-QCI/qcor/issues/76
Looks like there is an interference when qjit is destroyed (probably related to some static data structures in LLVM JIT have been updated)
We don't have this issue for QJIT kernels in the Python global scope (normal use cases), but in unit tests, we define test kernels in local scopes, thus seeing this problem. Thus, the fix is to cache all the Python QJIT objects to extend their lifetime.
=> Fix SegFault in QJIT tests

lib/quasimo/impls/cost_evaluator/time_series_iqpe.cpp, runtime/qrt/impls/nisq/nisq_qrt.cpp
- Update PauliOp terms to `std::map` (changes in XACC)
- Fix an edge case of 0/0. Gcc seems to be able to handle it just fine, but Clang returns `nan`.
Depends on https://github.com/eclipse/xacc/pull/382
=> Fixes for Clang toolchain

runtime/qrt/impls/nisq/CMakeLists.txt, runtime/qrt/impls/nisq/nisq_qrt.cpp, runtime/qrt/impls/nisq/tests/CMakeLists.txt, runtime/qrt/impls/nisq/tests/NisqQrtTester.cpp
Fixes https://github.com/ORNL-QCI/qcor/issues/92
Also, add a unit test to make sure QCOR's `exp` kernel matches the reference XACC circuit.
=> Improve qrt::exp() kernel composition time

handlers/token_collector/staq/staq_token_collector.cpp, handlers/token_collector/staq/tests/StaqTokenCollectorTester.in.cpp, handlers/token_collector/xasm/tests/XASMTokenCollectorTester.cpp, runtime/qrt/impls/ftqc/CMakeLists.txt, runtime/qrt/impls/ftqc/ftqc_qrt.cpp, runtime/qrt/impls/ftqc/tests/CMakeLists.txt, runtime/qrt/impls/ftqc/tests/FtqcQrtTester.cpp, runtime/qrt/impls/nisq/nisq_qrt.cpp, runtime/qrt/impls/nisq/tests/NisqQrtTester.cpp, runtime/qrt/qrt.cpp, runtime/qrt/qrt.hpp, runtime/qrt/qrt_mapper.hpp
- Add `reset` to QCOR's runtime (both `nisq` and `ftqc`).
- Update XASM and Staq token collectors to handle reset instruction.
- Add tests for token collectors and runtimes.
=> Add Reset instruction

python/tests/CMakeLists.txt, python/tests/test_jit_decompose.py, python/tests/test_jit_nested.py, python/tests/test_jit_pass_manager.py, python/tests/test_jit_simple.py, python/tests/test_kernel_builder.py, python/tests/test_kernel_ftqc.py, python/tests/test_openfermion_integration.py, python/tests/test_qcor_spec_api.py, python/tests/test_quasimo.py
- The hard failure of `qcor_python_jit_nested_kernels` test is fixed by https://github.com/eclipse/xacc/pull/409
- Enable `faulthandler` in our Python tests so that we can see the stack trace if a fault occurs during testing.
- Fix the test condition (more relaxed) in a unitary decomposing test (since the fidelity of the decomposition is not perfect).
- Re-enable two Python tests.
=> Re-enable some Python tests

handlers/token_collector/pyxasm/pyxasm_visitor.hpp, handlers/token_collector/pyxasm/tests/PyXASMTokenCollectorTester.cpp, python/tests/test_jit_kernel_signature.py
This turns out to be quite simple since we know all the local variables (including those from kernel arguments).
Hence, using that to choose b/w '.' and '::'.
=> Add ctrl and adjoint for KernelSignature

examples/bell/bell_control.cpp, python/py-qcor.cpp, python/tests/test_jit_simple.py
Also, add qubit type to PyQJIT arg type and operator[] binding.
Depends on https://github.com/eclipse/xacc/pull/436
=> Added an example and a test of control bit from a different qreg

python/tests/CMakeLists.txt, python/tests/test_compute_action.py, runtime/kernel/quantum_kernel.hpp
During kernel control: check if we are in a compute block. 
If so, temporarily disable compute segment flag to create a C-U circuit but need to mark all of the instructions as inside compute segment **afterward**.
No need for special treatment for single instruction kernels anymore.
=> Handle control modifier within a compute segment

examples/CMakeLists.txt, examples/bell/bell_control.cpp, examples/qpu_lambda/grover_lambda_oracle.cpp, examples/qpu_lambda/lambda_test.cpp, examples/qpu_lambda/lambda_test_bell.cpp, handlers/qcor_syntax_handler.cpp, handlers/token_collector/helper/token_collector_helper.cpp, handlers/token_collector/pyxasm/pyxasm_token_collector.cpp, handlers/token_collector/pyxasm/pyxasm_token_collector.hpp, handlers/token_collector/quil/quil_token_collector.cpp, handlers/token_collector/quil/quil_token_collector.hpp, handlers/token_collector/staq/staq_token_collector.cpp, handlers/token_collector/staq/staq_token_collector.hpp, handlers/token_collector/token_collector.hpp, handlers/token_collector/token_collector_util.cpp, handlers/token_collector/unitary/unitary_token_collector.cpp, handlers/token_collector/unitary/unitary_token_collector.hpp, handlers/token_collector/xasm/xasm_token_collector.cpp, handlers/token_collector/xasm/xasm_token_collector.hpp, runtime/jit/qcor_jit.hpp, runtime/jit/qcor_jit.in.cpp, runtime/kernel/quantum_kernel.hpp, runtime/utils/qcor_utils.hpp
Refactor kernel util API (control, adjoint, observe, print, etc.) to common functions with KernelSignature as the base.
Audit and fix qpu_lambda call chain to guarantee perfect type forwarding.
Add validation tests.
=> Refactor quantum kernel impls

examples/CMakeLists.txt, examples/qpu_lambda/deuteron_vqe.cpp, runtime/jit/qcor_jit.hpp, runtime/kernel/quantum_kernel.hpp
I forgot to put the observable argument in the call.
Also, disable `qpu_lambda` `arg&&` forwarding since it doesn't work properly with by-value lambda function arguments (not captured). This is a regression that I introduced when trying to forward qpu_lambda arguments.
Hence, this will make using `qpu_lambda` (non-copyable) as arguments illegal. Disable these tests for now.
=> Fixed a bug during QuantumKernel refactor

handlers/token_collector/pyxasm/pyxasm_visitor.hpp, python/tests/test_jit_kernel_signature.py
Check the list of kernels in translation unit to add parent_kernel argument in addition to qreg type checking.
=> Fixed https://github.com/ORNL-QCI/qcor/issues/143

examples/CMakeLists.txt, examples/qpu_lambda/deuteron_vqe.cpp, examples/qpu_lambda/lambda_test.cpp, runtime/jit/qcor_jit.hpp, runtime/kernel/quantum_kernel.hpp
Fixing an issue with type-forwarding in qpu_lambda. 
The final invoke relies on template type deduction to cast the C-style function pointer. 
Hence, workaround by using consistent reference types.
=> Consistent type forwarding for qpu_lambda

examples/CMakeLists.txt, examples/qpu_lambda/deuteron_vqe_obj_func.cpp, runtime/kernel/quantum_kernel.hpp, runtime/objectives/objective_function.hpp
Related to https://github.com/ORNL-QCI/qcor/issues/134
qpu_lambdas taking double or vector<double> can be used directly. Other qpu_lambda signatures must provide an ArgsTranslator.
=> createObjectiveFunction to support qpu_lambda ansatz

examples/CMakeLists.txt, examples/ctrl-gates/hadamard_test.cpp, runtime/qrt/impls/nisq/nisq_qrt.cpp, runtime/qrt/impls/nisq/tests/NisqQrtTester.cpp
Fixed https://github.com/ORNL-QCI/qcor/issues/149
exp_i_theta needs to work at the qubit level to reflect the actual qubit addresses in case the register is an alias.
=> Fixed exp_i_theta with alias registers

examples/CMakeLists.txt, examples/hybrid/deuteron_h2_vqe.cpp, examples/simple/gradients_optimization.cpp, examples/simple/simple-objective-function.cpp, python/py-qcor.cpp, python/qcor.in.py, python/tests/CMakeLists.txt, python/tests/test_autograd_opt.py, runtime/CMakeLists.txt, runtime/kernel/quantum_kernel.hpp, runtime/objectives/CMakeLists.txt, runtime/objectives/gradient_function.cpp, runtime/objectives/gradient_function.hpp, runtime/objectives/gradients/CMakeLists.txt, runtime/objectives/gradients/FiniteDifference/CMakeLists.txt, runtime/objectives/gradients/FiniteDifference/FiniteDifferenceGradients.cpp, runtime/objectives/gradients/FiniteDifference/manifest.json, runtime/objectives/objective_function.hpp, runtime/objectives/vqe/vqe.cpp
Related to https://github.com/ORNL-QCI/qcor/issues/141
- Put gradient calculation into a separate service interface.
- Support in ObjFunction as well as QuantumKernel
- Add simple python binding for QJIT.
There are some next steps that will be addressed later, e.g. qpu_lambda, don't need to use XACC's Algorithm Gradient.
=> First pass of better support for gradients

handlers/qcor_syntax_handler.cpp, handlers/token_collector/pyxasm/pyxasm_visitor.hpp, python/py-qcor.cpp, python/qcor.in.py, python/tests/test_jit_kernel_signature.py, runtime/kernel/quantum_kernel.hpp
Fixed https://github.com/ORNL-QCI/qcor/issues/156
- Python: parse List<KernelSignature> type annotation and convert it to a list of function pointers.
- C++ (syntax handler): when unpacking from Hetmap, parse the type string and convert from void* to KernelSignature and construct the vector.
Notes:
- Since the KernelSignatures are in a vector, we cannot reliably use the list of kernel arguments to add kernel names to the list of kernels in the translation unit anymore. Instead, add a variadic method to iterate over the parameter pack and set the KernelSignature `parent_kernel`. We extend KernelSignature to support an `operator()` w/o an input Composite. In that case, just use the set `parent_kernel` member instead. 
- Also fixed a bug in PyXASM visitor failed to register for loop …
=> Support List<KernelSignature>

examples/qsharp/NISQ/bell.qs, examples/qsharp/NISQ/bell_driver.cpp, examples/qsharp/NISQ/deuteron.qs, examples/qsharp/NISQ/qft.qs, examples/qsharp/NISQ/qft_driver.cpp, examples/qsharp/NISQ/vqe_driver.cpp, handlers/qcor_syntax_handler.cpp, mlir/qir_qrt/CMakeLists.txt, mlir/qir_qrt/qir-types.hpp, mlir/qir_qrt/qir_nisq_kernel_utils.hpp
This util will wrap a QIR kernel in a QCOR's `QuantumKernel`
It requires the first argument is a Qubit array (mapped to the `qreg`)
Update Q# examples that use this NISQ interop util.
=> Refactor the QIR-NISQ util

mlir/dialect/lib/Quantum/QuantumDialect.cpp, mlir/parsers/qasm3/tests/test_optimization.cpp, mlir/parsers/qasm3/utils/expression_handler.cpp, mlir/parsers/qasm3/visitor_handlers/loop_stmt_handler.cpp, mlir/parsers/qasm3/visitor_handlers/measurement_handler.cpp, mlir/parsers/qasm3/visitor_handlers/quantum_instruction_handler.cpp, mlir/tools/qcor-mlir-tool.cpp, mlir/transforms/optimizations/SimplifyQubitExtractPass.cpp, mlir/transforms/optimizations/SimplifyQubitExtractPass.hpp, mlir/transforms/pass_manager.hpp, mlir/transforms/quantum_to_llvm.cpp, tools/driver/qcor.in
Fixed https://github.com/ORNL-QCI/qcor/issues/178
Partially https://github.com/ORNL-QCI/qcor/issues/172 
- Convert the range-based for loops into affine for loops if possible. This is the first step to convert the whole QASM3 handler to use the affine dialect for control flows.
- Passing `-Ox` from main qcor command line to the mlir tool and a couple of other useful options. Turn on quantum optimization if any Clang optimization level is set or the `q-optimize` flag is set.
=> QASM3 to use Affine for loops and passing optimization CLI options

mlir/parsers/qasm3/tests/test_alias_handler.cpp, mlir/parsers/qasm3/tests/test_optimization.cpp, mlir/parsers/qasm3/utils/qasm3_utils.cpp, mlir/parsers/qasm3/utils/qasm3_utils.hpp, mlir/parsers/qasm3/utils/symbol_table.hpp, mlir/parsers/qasm3/visitor_handlers/alias_handler.cpp, mlir/parsers/qasm3/visitor_handlers/quantum_instruction_handler.cpp, mlir/transforms/optimizations/IdentityPairRemovalPass.cpp, mlir/transforms/optimizations/IdentityPairRemovalPass.hpp, mlir/transforms/optimizations/RemoveUnusedQIRCallsPass.cpp, mlir/transforms/pass_manager.hpp
- Adding a simple back-to-back qubit reset simplification pass (to become only 1 reset).
- This pass broke the alias test and uncovered a genuine bug (https://github.com/ORNL-QCI/qcor/issues/186)
- Fixed https://github.com/ORNL-QCI/qcor/issues/186: alias qubits to track their root qubits (enhance the `SymbolTable` to be a custom struct while keeping all the map-like behaviors); alias (slicing/concat) handlers to track the alias references in this `SymbolTable`.  
- Prevent name clashes b/w qubit-in-array symbol names (internal) and user-defined variables: use `%` character for internal symbols.
=> Add Reset optimization pass and handling qubit SSA variables in array aliasing

mlir/parsers/qasm3/tests/test_optimization.cpp, mlir/parsers/qasm3/utils/symbol_table.cpp, mlir/parsers/qasm3/utils/symbol_table.hpp, mlir/parsers/qasm3/visitor_handlers/loop_stmt_handler.cpp
- Refactor the `evaluate_constant_integer_expression` util to allow for a safe (no throwing) check.
- Loop handler to check whether the loop bounds could be const-eval.
-> Fixed https://github.com/ORNL-QCI/qcor/issues/180: This will bypass the global `memref` loading -> make the affine loop const at MLIR level -> enable unrolling at MLIR level.
- Add simple tests.
=> Consteval loop vars if possible

mlir/parsers/qasm3/tests/test_subroutine.cpp, mlir/parsers/qasm3/utils/expression_handler.cpp
- Subroutine invocation needs to load `memref` arguments similar to the classical extern kernel invocation.
- Add a simple test.
=> OpenQASM3: Fix subroutine invoke

handlers/qcor_syntax_handler.cpp, handlers/token_collector/helper/token_collector_helper.cpp
Currently, the SyntaxHandler generates code for kernels which runs runs
the PassManager after every kernel invocation, even when there is a
parent kernel. Avoid this by running the PassManager only when
optimize_only || is_callable.
Update the code used for compute-action blocks as well, because they
were also triggering the original issue.
Fixes #196
=> Run PassManager in SyntaxHandler only on top-level circuit

runtime/jit/qcor_jit.in.cpp
=> JIT extract_composite to apply passes similar to C++ print_kernel

mlir/qir_qrt/qir-qrt.cpp, runtime/qrt/impls/ftqc/CMakeLists.txt, runtime/qrt/impls/ftqc/ftqc_qrt.cpp, runtime/qrt/impls/ftqc/tracer/ResourcesTracerAccelerator.cpp, runtime/qrt/impls/ftqc/tracer/ResourcesTracerAccelerator.hpp, runtime/qrt/qrt.cpp, runtime/qrt/qrt.hpp
Using an `Accelerator` is the least invasive way to do this, hence requires the least code changes.
Usage: `-qrt ftqc -qpu tracer`
Users can also provide custom measure probability to control measure emulation (default is return 0 for all measures)
=> Work on a simple resources estimator Accelerator

mlir/parsers/qasm3/CMakeLists.txt, mlir/parsers/qasm3/qasm3_visitor.hpp, mlir/parsers/qasm3/tests/test_control_directives.cpp, mlir/parsers/qasm3/tests/test_loop_stmts.cpp, mlir/parsers/qasm3/tests/test_optimization.cpp, mlir/parsers/qasm3/utils/expression_handler.cpp, mlir/parsers/qasm3/utils/qasm3_utils.cpp, mlir/parsers/qasm3/utils/symbol_table.cpp, mlir/parsers/qasm3/utils/symbol_table.hpp, mlir/parsers/qasm3/visitor_handlers/conditional_handler.cpp, mlir/parsers/qasm3/visitor_handlers/control_directive_handler.cpp, mlir/parsers/qasm3/visitor_handlers/loop_stmt_handler.cpp, mlir/parsers/qasm3/visitor_handlers/measurement_handler.cpp, mlir/parsers/qasm3/visitor_handlers/qcor_expect_handler.cpp, mlir/parsers/qasm3/visitor_handlers/quantum_instruction_handler.cpp, mlir/parsers/qasm3/visitor_handlers/subroutine_handler.cpp, mlir/transforms/lowering/CreateStringLiteralOpLowering.cpp, mlir/transforms/optimizations/CphaseRotationMergingPass.cpp, mlir/transforms/optimizations/CphaseRotationMergingPass.hpp, mlir/transforms/optimizations/SimplifyQubitExtractPass.cpp, mlir/transforms/pass_manager.hpp
1. Robust handling of qubit SSA use-def chain (related to https://github.com/ORNL-QCI/qcor/issues/187)
- Update Symbol Table and QASM3 util (get_or_extract_qubit) to be region-aware: qubit values that are produced by QVS Ops inside a region (If body, Loop body) cannot be continued/chained outside that region. Instead, need to re-extract from the qreg.
- Fix a couple of places that we don't follow the convention of `qreg%id` to track qubit vars, making the use-def chain inconsistent.
- The extract qubit optimization will also respect this region rule. If the loop has been unrolled into the main region, we can still optimize the use-def chain.
2. Using affine/scf dialect to handle control flow.
- Following the example in https://llvm.discourse.group/t/dynamic-control-flow-break-like-operatio …
=> OpenQASM3 compiler update

mlir/parsers/qasm3/tests/test_complex_arithmetic.cpp, mlir/parsers/qasm3/utils/expression_handler.cpp
The reason is that CFG block-based implementation is not compatible when this is nested inside a loop construct.
e.g., YieldOp at the end needs to be aware of which block is the exit one.
This is a regression bug from the loop handling conversion to Affine/SCF.
=> Using SCF ForOp to compute the integer power

mlir/parsers/qasm3/examples/adder.qasm, mlir/parsers/qasm3/tests/test_subroutine.cpp, mlir/parsers/qasm3/utils/expression_handler.cpp, mlir/transforms/lowering/InstOpLowering.cpp, mlir/transforms/lowering/QallocOpLowering.cpp, tools/driver/qcor.in
Fixes a couple of minor bugs: LoadOp on non-memref types, handling of integer bit-width in casting.
Also, adding the ability to use a different object linker other than the clang-csp in the driver.
=> Added QASM3 adder example

examples/mirror_validation/validate_execution.py, lib/mirror_rb/mirror_circuit_rb.cpp, python/py-qcor.cpp
- Reduce the default number of runs for smaller circuits.
- Reduce debug logging.
=> Added python example for mirror circuit validation mode

mlir/parsers/qasm3/tests/test_loop_stmts.cpp, mlir/parsers/qasm3/utils/qasm3_utils.cpp, mlir/parsers/qasm3/visitor_handlers/loop_stmt_handler.cpp
The unnecessary casting ops between integer and index types cause the Affine for validation to fail. This only occurs when the constant values are created inside another affine scope.
Fixing the const index value builder to create the index const directly and the loop statement handler in the range-based case to create index type.
=> Fixed nested range-based for loops

python/py-qcor.cpp, python/qcor.in.py
Forward the `qreg` arg from python to cpp so that the child buffers are attached to it.
Users may want to use this data for further analysis besides the accumulated energy value.
=> Ability to get term execution data when using qjit.observe()

mlir/parsers/qasm3/tests/test_declaration.cpp, mlir/parsers/qasm3/utils/expression_handler.cpp
This is my attempt at fixing #251. Currently, writing the following OpenQASM 3:
const pos = 2;
bit c[4];
print(c[pos]);
generates the following invalid MLIR:
%3 = index_cast %1 : memref<ui32> to index
Instead, we need to load the memref first:
%3 = load %1[] : memref<i64>
%4 = index_cast %3 : i64 to index
Add a check and a unit test for this.
I added a unit test for this and ran the unit tests with `ctest` (some unrelated QJIT tests failed with linker errors, but they also failed on `master` for me). I also manually tested with the code from #251 as well as using a constant which could trigger the same problem:
```
OPENQASM 3;
const pos = 2;
bit c[4] = "0101";
print(c[pos]);
```
=> qasm3 parser: Support indexing classical arrays with variables
